name: Set Environment Variables

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "OPEN_WEATHER_MAP_API_KEY=${{ secrets.OPEN_WEATHER_MAP_API_KEY }}" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "OPEN_WEATHER_MAP_API_KEY: $OPEN_WEATHER_MAP_API_KEY"
